### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1achy** [cherezov/orvibo#1]
It is work grab IR and send Ir code but after 5 time send It i have this error:

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Mar  8 19:46:46 2016 from 192.168.1.21
root@raspberrypi:~# python /usr/share/openhab/addons/orvibo.py -i 192.168.1.26 -t /usr/share/openhab/addons/ir/test.ir
Traceback (most recent call last):
  File "/usr/share/openhab/addons/orvibo.py", line 519, in <module>
    d = Orvibo.discover(ip)
  File "/usr/share/openhab/addons/orvibo.py", line 241, in discover
    with _orvibo_socket() as s:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/share/openhab/addons/orvibo.py", line 99, in _orvibo_socket
    sock.bind(('', PORT))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by 1achy** [comment]
I use this command : 
python /usr/share/openhab/addons/orvibo.py -i 192.168.1.26 -t /usr/share/openhab/addons/ir/test.ir
python /usr/share/openhab/addons/orvibo.py -i 192.168.1.26 -e /usr/share/openhab/addons/ir/test.ir

**Comment by cherezov** [comment]
Discussed on OpenHAB forum [thread](https://community.openhab.org/t/ir-blaster-home-automation-wiwo-orvibo-s20/4062/28).OpenHAB configuration issue.
