### ISSUE TITLE
keep_connection error

### ISSUE THREAD

**Issue by rghiglianovich** [cherezov/orvibo#12]
Hi, 
If I use orvibo.py in Console mode it works good, the AllOne works and beams.

I am trying to use it as a module to eliminate the long lag  so I need to activate the keep_connection option. 

But it doesn't work :(

After instantiated the orvibo object, I set up the keep_connect to true but I get an error:

running this:

import orvibo
from orvibo.orvibo import Orvibo

orv = Orvibo('192.168.168.115','accf232991f4', 'irda')
orv.keep_connection = True

I get :

File "test.py", line 7, in <module>
    orv.keep_connection = True
  File "/Users/riccardo/orviboServer/orvibo/orvibo/orvibo.py", line 309, in keep_connection
    if self.__subscribe(self.__socket) is None:
  File "/Users/riccardo/orviboServer/orvibo/orvibo/orvibo.py", line 382, in __subscribe
    subscr_packet.send(s)
  File "/Users/riccardo/orviboServer/orvibo/orvibo/orvibo.py", line 191, in send
    sock.sendto(bytearray(self.data), (self.ip, PORT))
OSError: [Errno 56] Socket is already connected

python version:

Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 08:49:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

RIc

**Comment by liorsh69** [comment]
+1
No luck trying to keep the connection.
AllOne is disconnecting after several hours.

Also tried to send dummy IR code every 10 minutes to force the device to stay connected to the network - didn't work as well.

**Comment by ysraibagkar** [comment]
Did you able to resolve this issue????
I am facing the same issue.

```
[10:38:59] openhabian@Raiba-SmartHome:/etc/openhab2/orvibo$ python3 orvibo.py
Traceback (most recent call last):
  File "orvibo.py", line 706, in <module>
    for d in Orvibo.discover().values():
  File "orvibo.py", line 330, in discover
    with _orvibo_socket() as s:
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "orvibo.py", line 135, in _orvibo_socket
    sock = _create_orvibo_socket() if external_socket is None else external_socket
  File "orvibo.py", line 130, in _create_orvibo_socket
    sock.bind((ip, PORT))
OSError: [Errno 98] Address already in use
```
